# Complete Enhanced DoMINO Configuration - Validation Processing

data_processor:
  kind: ahmed
  use_enhanced_features: true
  input_dir: /data/ahmed_data/organized/val/fine/
  coarse_input_dir: /data/ahmed_data/organized/val/coarse/
  output_dir: /data/ahmed_data/processed/val/
  surface_variables: [p, wallShearStress_0, wallShearStress_1, wallShearStress_2]
  force_reprocess: true
  num_processors: 8
  use_cache: false

model:
  model_type: surface
  enhanced_model:
    surface_input_features: 8
    coarse_to_fine:
      use_spectral: true
      use_residual: true

variables:
  surface:
    solution:
      pMean: scalar
      wallShearStressMean: vector
    enhanced_features:
      input_feature_count: 8
      coarse_variable_mapping:
        pMean: p
        wallShearStressMean: wallShearStress
  volume:
    solution:
      UMeanTrim: vector
      pMeanTrim: scalar
      nutMeanTrim: scalar

data:
  bounding_box:
    max: [6.0, 1.0, 1.4]
    min: [-4.0, -1.0, 0.0]
  bounding_box_surface:
    max: [1.0, 0.4, 0.5]
    min: [-1.5, -0.4, 0.0]
  gpu_preprocessing: true
  gpu_output: true

domain_parallelism:
  domain_size: 1
  shard_grid: false
  shard_points: false

# Project info
project:
  name: Ahmed_Dataset
exp_tag: enhanced_val_processing
